on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Store secret in file
        id: store
        run: |-
          echo ${{secrets.YOUR_SECRET }} | sed 's/./& /g'
